version: "3.9"
services:
  webapp: # the name of your service
    build:
      context: . # Docker Build context
      dockerfile: Dockerfile # Dockerfile path
    image: your-image-name:tag # image name and tag
    ports:
      - "3000:80" # port mapping